
# This file is automatically generated, you probably don't want to edit this

ridgeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ridgeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            group = NULL,
            scale = 1.5,
            gradient = FALSE,
            naOmit = FALSE,
            title = "",
            titleAlign = "center",
            titleFontSize = 16,
            titleFontFace = "plain",
            subtitle = "",
            subtitleAlign = "left",
            subtitleFontSize = 16,
            subtitleFontFace = "plain",
            caption = "",
            captionAlign = "right",
            captionFontSize = 12,
            captionFontFace = "plain",
            xLabel = "",
            xLabelAlign = "center",
            xLabelFontSize = 16,
            xLabelFontFace = "plain",
            yLabel = "",
            yLabelAlign = "center",
            yLabelFontSize = 16,
            yLabelFontFace = "plain",
            titleType = "title",
            yAxisLabelFontSize = 12,
            yAxisLabelRotation = 0,
            xAxisLabelFontSize = 12,
            xAxisLabelRotation = 0, ...) {

            super$initialize(
                package="scatr",
                name="ridge",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..scale <- jmvcore::OptionNumber$new(
                "scale",
                scale,
                default=1.5,
                min=0)
            private$..gradient <- jmvcore::OptionBool$new(
                "gradient",
                gradient,
                default=FALSE)
            private$..naOmit <- jmvcore::OptionBool$new(
                "naOmit",
                naOmit,
                default=FALSE)
            private$..title <- jmvcore::OptionString$new(
                "title",
                title,
                default="")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..titleFontSize <- jmvcore::OptionNumber$new(
                "titleFontSize",
                titleFontSize,
                default=16)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..subtitle <- jmvcore::OptionString$new(
                "subtitle",
                subtitle,
                default="")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="left")
            private$..subtitleFontSize <- jmvcore::OptionNumber$new(
                "subtitleFontSize",
                subtitleFontSize,
                default=16)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..caption <- jmvcore::OptionString$new(
                "caption",
                caption,
                default="")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="right")
            private$..captionFontSize <- jmvcore::OptionNumber$new(
                "captionFontSize",
                captionFontSize,
                default=12)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..xLabel <- jmvcore::OptionString$new(
                "xLabel",
                xLabel,
                default="")
            private$..xLabelAlign <- jmvcore::OptionList$new(
                "xLabelAlign",
                xLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..xLabelFontSize <- jmvcore::OptionNumber$new(
                "xLabelFontSize",
                xLabelFontSize,
                default=16)
            private$..xLabelFontFace <- jmvcore::OptionList$new(
                "xLabelFontFace",
                xLabelFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..yLabel <- jmvcore::OptionString$new(
                "yLabel",
                yLabel,
                default="")
            private$..yLabelAlign <- jmvcore::OptionList$new(
                "yLabelAlign",
                yLabelAlign,
                options=list(
                    "left",
                    "center",
                    "right"),
                default="center")
            private$..yLabelFontSize <- jmvcore::OptionNumber$new(
                "yLabelFontSize",
                yLabelFontSize,
                default=16)
            private$..yLabelFontFace <- jmvcore::OptionList$new(
                "yLabelFontFace",
                yLabelFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold-italic"),
                default="plain")
            private$..titleType <- jmvcore::OptionList$new(
                "titleType",
                titleType,
                options=list(
                    "title",
                    "subtitle",
                    "caption",
                    "xTitle",
                    "yTitle"),
                default="title")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)

            self$.addOption(private$..var)
            self$.addOption(private$..group)
            self$.addOption(private$..scale)
            self$.addOption(private$..gradient)
            self$.addOption(private$..naOmit)
            self$.addOption(private$..title)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..subtitle)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..caption)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..xLabel)
            self$.addOption(private$..xLabelAlign)
            self$.addOption(private$..xLabelFontSize)
            self$.addOption(private$..xLabelFontFace)
            self$.addOption(private$..yLabel)
            self$.addOption(private$..yLabelAlign)
            self$.addOption(private$..yLabelFontSize)
            self$.addOption(private$..yLabelFontFace)
            self$.addOption(private$..titleType)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelRotation)
        }),
    active = list(
        var = function() private$..var$value,
        group = function() private$..group$value,
        scale = function() private$..scale$value,
        gradient = function() private$..gradient$value,
        naOmit = function() private$..naOmit$value,
        title = function() private$..title$value,
        titleAlign = function() private$..titleAlign$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleFontFace = function() private$..titleFontFace$value,
        subtitle = function() private$..subtitle$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        caption = function() private$..caption$value,
        captionAlign = function() private$..captionAlign$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionFontFace = function() private$..captionFontFace$value,
        xLabel = function() private$..xLabel$value,
        xLabelAlign = function() private$..xLabelAlign$value,
        xLabelFontSize = function() private$..xLabelFontSize$value,
        xLabelFontFace = function() private$..xLabelFontFace$value,
        yLabel = function() private$..yLabel$value,
        yLabelAlign = function() private$..yLabelAlign$value,
        yLabelFontSize = function() private$..yLabelFontSize$value,
        yLabelFontFace = function() private$..yLabelFontFace$value,
        titleType = function() private$..titleType$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value),
    private = list(
        ..var = NA,
        ..group = NA,
        ..scale = NA,
        ..gradient = NA,
        ..naOmit = NA,
        ..title = NA,
        ..titleAlign = NA,
        ..titleFontSize = NA,
        ..titleFontFace = NA,
        ..subtitle = NA,
        ..subtitleAlign = NA,
        ..subtitleFontSize = NA,
        ..subtitleFontFace = NA,
        ..caption = NA,
        ..captionAlign = NA,
        ..captionFontSize = NA,
        ..captionFontFace = NA,
        ..xLabel = NA,
        ..xLabelAlign = NA,
        ..xLabelFontSize = NA,
        ..xLabelFontFace = NA,
        ..yLabel = NA,
        ..yLabelAlign = NA,
        ..yLabelFontSize = NA,
        ..yLabelFontFace = NA,
        ..titleType = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisLabelRotation = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelRotation = NA)
)

ridgeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ridgeResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Ridgeline Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=550,
                height=500,
                renderFun=".ridgePlot"))}))

ridgeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ridgeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "scatr",
                name = "ridge",
                version = c(1,0,0),
                options = options,
                results = ridgeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Ridgeline Plot
#'
#' 
#' @param data .
#' @param var .
#' @param group .
#' @param scale .
#' @param gradient .
#' @param naOmit .
#' @param title .
#' @param titleAlign .
#' @param titleFontSize .
#' @param titleFontFace .
#' @param subtitle .
#' @param subtitleAlign .
#' @param subtitleFontSize .
#' @param subtitleFontFace .
#' @param caption .
#' @param captionAlign .
#' @param captionFontSize .
#' @param captionFontFace .
#' @param xLabel .
#' @param xLabelAlign .
#' @param xLabelFontSize .
#' @param xLabelFontFace .
#' @param yLabel .
#' @param yLabelAlign .
#' @param yLabelFontSize .
#' @param yLabelFontFace .
#' @param titleType .
#' @param yAxisLabelFontSize .
#' @param yAxisLabelRotation .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelRotation .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image containing the ridgeline plot \cr
#' }
#'
#' @export
ridge <- function(
    data,
    var,
    group,
    scale = 1.5,
    gradient = FALSE,
    naOmit = FALSE,
    title = "",
    titleAlign = "center",
    titleFontSize = 16,
    titleFontFace = "plain",
    subtitle = "",
    subtitleAlign = "left",
    subtitleFontSize = 16,
    subtitleFontFace = "plain",
    caption = "",
    captionAlign = "right",
    captionFontSize = 12,
    captionFontFace = "plain",
    xLabel = "",
    xLabelAlign = "center",
    xLabelFontSize = 16,
    xLabelFontFace = "plain",
    yLabel = "",
    yLabelAlign = "center",
    yLabelFontSize = 16,
    yLabelFontFace = "plain",
    titleType = "title",
    yAxisLabelFontSize = 12,
    yAxisLabelRotation = 0,
    xAxisLabelFontSize = 12,
    xAxisLabelRotation = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ridge requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- ridgeOptions$new(
        var = var,
        group = group,
        scale = scale,
        gradient = gradient,
        naOmit = naOmit,
        title = title,
        titleAlign = titleAlign,
        titleFontSize = titleFontSize,
        titleFontFace = titleFontFace,
        subtitle = subtitle,
        subtitleAlign = subtitleAlign,
        subtitleFontSize = subtitleFontSize,
        subtitleFontFace = subtitleFontFace,
        caption = caption,
        captionAlign = captionAlign,
        captionFontSize = captionFontSize,
        captionFontFace = captionFontFace,
        xLabel = xLabel,
        xLabelAlign = xLabelAlign,
        xLabelFontSize = xLabelFontSize,
        xLabelFontFace = xLabelFontFace,
        yLabel = yLabel,
        yLabelAlign = yLabelAlign,
        yLabelFontSize = yLabelFontSize,
        yLabelFontFace = yLabelFontFace,
        titleType = titleType,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisLabelRotation = yAxisLabelRotation,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelRotation = xAxisLabelRotation)

    analysis <- ridgeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

